name: release
on:
  push:
    branches:
      - master
     

env:
  INFRASTRUCTURE_REPO: ${{ github.repository_owner }}/internship_devops_infrastructure
  IMAGE: internship_frontend 
  REGISTRY: bulbawarrior # registry url prefix without image name
     
jobs:
  Build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ github.sha }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Update helm charts in ${{ env.INFRASTRUCTURE_REPO }}
        uses: aurelien-baudet/workflow-dispatch@v2.1.1
        with:
          workflow: local release
          token: ${{ secrets.INFRASTRUCTURE_TOKEN }}
          repo: ${{ env.INFRASTRUCTURE_TOKEN }}
          inputs: '{"service_image_name":"${{ env.IMAGE }}", "registry_url":"${{ env.REGISTRY }}", "tag":"${{ github.sha }}"}'

